### ISSUE TITLE
OpenCATS upload CV file size error

### ISSUE THREAD

**Issue by dericlau** [opencats/OpenCATS#222]
I have installed the latest OpenCATS on a new Ubuntu 10.04 machine. 

When I upload a CV (over 2 to 3 MB ) of a candidate, it mentioned

A File Error has Occurred
There was a problem when CATS attempted to process the file you selected. File size is greater than system-wide size limit. File errors are sometimes caused by high Internet traffic or older web browsers. The latest version of the Mozilla Firefox© browser is recommended.

May I know how I could solve it...?

![screen shot 2017-03-03 at 3 41 46 pm](https://cloud.githubusercontent.com/assets/26128292/23542437/07f10348-0028-11e7-9846-3fefdd5676b1.png)

**Comment by RussH** [comment]
Hi,

typically this is caused by the php.ini max_file_upload default setting of
2Mb

some quick googling reveals..

You will need to change some or all of the following in php.ini


memory_limit = 32M
upload_max_filesize = 24M
post_max_size = 32M

After making these changes, you will need to restart Apache.
Additional information

If the *upload_max_filesize* is larger than *post_max_size*, you must
increase *post_max_size* so that it is bigger than *upload_max_size*.

If the value of *post_max_size* is larger than *memory_limit*, you must
increase *memory_limit* so that it is larger than *post_max_size*.






----
Russ

**Comment by dericlau** [comment]
Thank you.. Let me try it later...

**Comment by RussH** [comment]
Closing - no response.

**Comment by rizwannadeem2017** [comment]
Hi,

I'm facing the same issue while uploading resume upto 2MB then i changed PHP.INI file as below. 

memory_limit = 32M
upload_max_filesize = 24M
post_max_size = 32M

after that rebooted services and server but now i m getting this error

![image](https://user-images.githubusercontent.com/32321199/32643470-837ac9d6-c5fd-11e7-9dd8-8d57421a1227.png)
