### ISSUE TITLE
Bulk Remove Candidates Data

### ISSUE THREAD

**Issue by nlargebiz** [opencats/OpenCATS#320]
Hello opencats

What do I need to do in order to drop all of the candidate data in my database?  I did an import incorrectly and need to remove just that data without having to delete each of them individually.

### Expected behavior and actual behavior.
I should be able to remove multiple candidates from the system in one operation. 

### Steps to reproduce the problem.
N/A

### What version of opencats are you running? WAMP or LAMP? 
Linux CentOS 7

### attach appropriate error logs. Please attach [apache/mysql] error/access logs as needed.
N/A

**Comment by RussH** [comment]
Hi, this is really one for the user support forums - however if you've imported via the settings / admin menu option, if you revisit there then you will see there's an option to revert the import. Otherwise it's simplest to delete all the entries from the candidate table via phpmyadmin - or drop and recreate it. This isn't something we 'd expose in the app as an option to prevent accidental / malicious database deletion!

**Comment by nlargebiz** [comment]
Thanks Russ. Could you please supply me with the link to the user support forum that I should be posting these too.

Nick.

**Comment by RussH** [comment]
Hey nick - it's at http://forums.opencats.org

**Comment by skrchnavy** [comment]
Btw, all relevant links are at: https://github.com/opencats/OpenCATS and also on http://www.opencats.org/

**Comment by nlargebiz** [comment]
Thanks again Russ for your prompt replies.  Much appreciated :)
