### ISSUE TITLE
form error - body empty 

### ISSUE THREAD

**Issue by yvsingh1001** [opencats/OpenCATS#373]
While sending mass mail I am getting error  "form error - you must enter the body for your email " when I click "send mail" but  i have already filled the body. 
screenshot for same is - http://gig.vin/6e8142a9787f

When i  click the "send mail" again. it redirects me to  Success Screen - http://gig.vin/44367b3fc74f

But none of the recept receives the email

**Comment by RussH** [comment]
Hi @yvsingh1001 can you provide the info requested when an issue is opened please so that we can investigate;
Expected behavior and actual behavior.
Steps to reproduce the problem.
What version of opencats are you running?
Release or downloaded from Git?
WAMP or LAMP?
What version of PHP and MySQL are you running
attach appropriate error logs. Please attach [apache/mysql] error/access logs as needed.

**Comment by RussH** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
