### ISSUE TITLE
Opencats Error while creating company

### ISSUE THREAD

**Issue by EktaPro** [opencats/OpenCATS#375]
Hello All,

I have install Opencats and getting error while creating new company. I get whole blue wide line instead of form as shown as below screenshot
Plz someone guide me to resolve this issue.

![opencats](https://user-images.githubusercontent.com/42994840/45078202-ff8db100-b10c-11e8-9430-195b4d1788a2.PNG)

**Comment by RussH** [comment]
Hi, 

looks like it's a PHP version error. Can you confirm you're on a supported version of PHP please?

**Comment by EktaPro** [comment]
Hi,
I am using php version 5.6.37. 
And documents says 'Opencats has a minimum supported PHP version of PHP 5.5, and are working towards full PHP 7 compatibility.'

**Comment by RussH** [comment]
Sorry I realise where I've seen this before.. Can you confirm that youv'e installed the full version from releases and not downloaded from the repo? If youv'e downloaded from the repo, you will need to run composer to install all the required dependencies.

**Comment by EktaPro** [comment]
Hi,
I have installed the full version. I have tried installation 2 times, but still getting same error.

**Comment by EktaPro** [comment]
Hi, 
Can u plz tell me which composer I will have to run to install all dependencies

**Comment by skrchnavy** [comment]
Please check log file for errors.

**Comment by RussH** [comment]
Hi @EktaPro Two things. Firstly - please can you provide the information that's normally requested when you create an issue;

Expected behavior and actual behavior.
->

Steps to reproduce the problem.
->

What version of opencats are you running?
->

Release or downloaded from Git?
->

WAMP or LAMP?
->

What version of PHP and MySQL are you running
->

attach appropriate error logs. Please attach [apache/mysql] error/access logs as needed.
->


Now - for composer, please see this issue. https://github.com/opencats/OpenCATS/issues/130#issuecomment-254228495

**Comment by EktaPro** [comment]
Hi, 
I have installed iconv and mbstring extensions, and than install composer. Issue solved. 
Thanks a lot for your support.
