### ISSUE TITLE
Can I add Captcha (or any similar features) on job submission page

### ISSUE THREAD

**Issue by Rami-Gaber** [opencats/OpenCATS#424]
Is it possible to add an extra layer of security in regard to job submissions done by candidates through the public job board? Something similar to Captcha..

**Comment by RussH** [comment]
I haven't because I use wordpress job manager as a front-end for opencats, and captcha is in there. However I don't see any reason you can't do it.

**Comment by Rami-Gaber** [comment]
Thanks alot for your appreciated kind responsiveness,Russ! 
Are you referring to https://wpjobmanager.com/ as WordPress Job Manager?

**Comment by RussH** [comment]
Yes, I configure the XML feed so that the web server picks it up - and then
refresh the xml feed every few minutes via a cron job. It's just one way to
do it.

Of course, that doesn't add applicants into the backend of opencats - it'll
send an application email notification, but I've always preferred some
separation between opencats being backend and secure, and an internet
facing (& less secure) webserver.


----
Russ

**Comment by Rami-Gaber** [comment]
Running opencats on both front/back ends is awesome, I mean speaking of convenience in terms of speed(handling requests), simplicity (UI) I love it the way it is. I have always been concerned about security so far a reinforced SSL across my domains/sub-domains and everything is being done using SSH...

**Comment by RussH** [comment]
final point then - please make sure you apply the minor changes to mitigate
XSS vulnerability in career portal:
https://github.com/opencats/OpenCATS/issues/406


----
Russ

**Comment by Rami-Gaber** [comment]
> Looks like this can be added to /lib/UserInterface.php line 384;
> return trim(htmlspecialchars ($request[$key]), ENT_QUOTES)

Are you referring to that change you mentioned on other post?

**Comment by RussH** [comment]
yes


----
Russ

**Comment by Rami-Gaber** [comment]
Great, I will surely do that. Thanks alot Russ!
