### ISSUE TITLE
MySQL error during mass import 

### ISSUE THREAD

**Issue by Rami-Gaber** [opencats/OpenCATS#426]
**ENVIRONMENT:**
CATS Version: 0.9.4
PHP: 5.6
MySQL: 7.0
Apache/2.4.18
Ubuntu16.04.1

**Issue Description:** MySQL error during mass import.
**Steps leading to the problem:**
1. Files were uploaded to the proper destination for mass import. 
![Screenshot 1](https://i.ibb.co/SvdSPkM/RG-0722.png)

2. I edited some of the imported resumes where I added first, last names and email.
![Screenshot 2](https://i.ibb.co/VJNsGV4/RG-0724.png)

3. Once I click on "Import candidates" I get a MySQL Error as follows:
![Screenshot 3](https://i.ibb.co/TrSQFzf/RG-0723.png)

UPDATE candidate SET date_created = "2019-04-07T01:13:58+00:00", date_modified = "2019-04-07T01:13:58+00:00" WHERE candidate_id = 35 AND site_id = 1

**Comment by skrchnavy** [comment]
What is your collation in DB and locale settings at system?

**Comment by Rami-Gaber** [comment]
**DB Collation**  utf_general_ci

**Localhost Database**
**Database server**

- Server: Localhost via UNIX socket
- Server type: MySQL
- Server version: 5.7.25-0ubuntu0.16.04.2 - (Ubuntu)
- Protocol version: 10
- User: root@localhost
- Server charset: UTF-8 Unicode (utf8)

**Web server**
Apache/2.4.18 (Ubuntu)
Database client version: libmysql - mysqlnd 5.0.12
PHP extension: mysqli Documentation
PHP version: 7.0.33-1+ubuntu16.04.1+deb.sury.org+1

**SQL Mode:**
STRICT_TRANS_TABLES,ALLOW_INVALID_DATES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

**Comment by RussH** [comment]
@Rami-Gaber is this sitll an issue?

**Comment by Rami-Gaber** [comment]
@RussH Yes it is still is unfortunately.

**Comment by RussH** [comment]
Okay, the MySQL server has different defaults these days than the MariaDB server. Otherwise it's  feature compatible. Can you possibly install MariaDB instead of MySQL?

**Comment by RussH** [comment]
The NO_ZERO_DATE mode affects whether the server permits '0000-00-00' as a valid date. Its effect also depends on whether strict SQL mode is enabled.

If this mode is not enabled, '0000-00-00' is permitted and inserts produce no warning.

If this mode is enabled, '0000-00-00' is permitted and inserts produce a warning.

If this mode and strict mode are enabled, '0000-00-00' is not permitted and inserts produce an error, unless IGNORE is given as well. For INSERT IGNORE and UPDATE IGNORE, '0000-00-00' is permitted and inserts produce a warning.

As of MySQL 5.7.4, NO_ZERO_DATE is deprecated. In MySQL 5.7.4 through 5.7.7, NO_ZERO_DATE does nothing when named explicitly. Instead, its effect is included in the effects of strict SQL mode. In MySQL 5.7.8 and later, NO_ZERO_DATE does have an effect when named explicitly and is not part of strict mode, as before MySQL 5.7.4. However, it should be used in conjunction with strict mode and is enabled by default. A warning occurs if NO_ZERO_DATE is enabled without also enabling strict mode or vice versa. For additional discussion, see SQL Mode Changes in MySQL 5.7.

Because NO_ZERO_DATE is deprecated, it will be removed in a future MySQL release as a separate mode name and its effect included in the effects of strict SQL mode.

From http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_no_zero_date

**Comment by RussH** [comment]
see here - https://stackoverflow.com/questions/22806870/incorrect-datetime-value-database-error-number-1292

**Comment by Rami-Gaber** [comment]
No more errors once I disabled the (sql mode). Thanks alot Russ.
