### ISSUE TITLE
[Feature] GDPR / DSGVO

### ISSUE THREAD

**Issue by ThomasKujawa** [opencats/OpenCATS#445]
a) Before sending the application, the applicant must read the privacy policy. It is best to use a field: 'Taken note of'.

b) By the applicant requesting all data stored about him (without comments / notes). Send by mail after approval by an admin.

c) After request by the applicant: deletion of all data stored about him (after a period of x months) and confirmation of the deletion by e-mail.

d) Question about rejection of an application whether the personal data for other possible positions may still be stored for a period of x months.

e) Ask after the x months whether the data may be stored for further x months.

**Comment by shantadam** [comment]
Hi Thomas,

Forgive me to interject.

  1.  Your below feature recommendation is missing context.
     *   In which context of the OpenCATS app you’re looking for the later feature?
  2.  What is the concern exactly, which triggered your below feature recommendation?
     *   Are you concerned about certain privacy policy compliance within your organization?
     *   Are there any publicly available audit standard procedure we should be aware about? If so, which one?

Regards,
Shant Adam

**Comment by ThomasKujawa** [comment]
> * In which context of the OpenCATS app you’re looking for the later feature?
> * What is the concern exactly, which triggered your below feature recommendation?
> * Are there any publicly available audit standard procedure we should be aware about? If so, which one? 

* the context is the compliance with the DSGVO / GDPR
* see above
* no, i don't think so.

**Comment by shantadam** [comment]
@ThomasKujawa, 

I'm glad you brought this regulatory compliance principles to the group's attention. I personally take regulatory compliance seriously, since to my belief no organization or institution should be subjected to unnecessary fines for non-compliancy with certain regulation, which lead to financial loss. 

GDPR (https://en.wikipedia.org/wiki/General_Data_Protection_Regulation) is a one serious matter, as the following list shows the fines tagged to certain authorities worldwide (http://enforcementtracker.com). 

Regardless of the necessity of having this feature in the app, this feature should be developed as a module, namely GDPR. My question is, should this GDPR module be optional for users to activate or deactivate?

**Comment by ThomasKujawa** [comment]
I am convinced that compliance with the rules is not only necessary for financial reasons, @shantadam. ;-) 

It should be optional, so that users of opencats who do not target Europeans can deactivate them.
