### ISSUE TITLE
Add Attachment to Candidate Application Received Send to Job Owner

### ISSUE THREAD

**Issue by Rami-Gaber** [opencats/OpenCATS#455]
Hello guys,

CATS Version: 0.9.4
Description: 
From: Administration: E-Mail Templates
Template Name: Candidate Application Received (Send to Owner of the Job Order from Career Portal)

The default template is set to:

> %DATETIME%
> 
> Dear %JBODOWNER%,
> 
> This e-mail is a notification that a candidate has applied to your job order through the online candidate portal.
> 
> Job Order: %JBODTITLE%
> Candidate Name: %CANDFULLNAME%
> Candidate URL: %CANDCATSURL%
> Job Order URL: %JBODCATSURL%
> 
> --
> CATS
> %SITENAME%
> 
I wish to also include candidate attachments (resume) to this email as well, but I dont find that on the  "Insert Mail Merge Fields" 

Appreciate your kind considerations.

Cheers,
Rami

**Comment by shantadam** [comment]
Thanks for the input, Rami.

Your request is not feasible, because attachments are external documents appended alongside the email.

The solution is simple, if the job order owner wants they can visualize the resume through the candidate’s profile page.

Regards,
Shant Adam


On Oct 9, 2019, at 11:09 AM, Rami-Gaber <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello guys,

CATS Version: 0.9.4
Description:
From: Administration: E-Mail Templates
Template Name: Candidate Application Received (Send to Owner of the Job Order from Career Portal)

The default template is set to:

%DATETIME%

Dear %JBODOWNER%,

This e-mail is a notification that a candidate has applied to your job order through the online candidate portal.

Job Order: %JBODTITLE%
Candidate Name: %CANDFULLNAME%
Candidate URL: %CANDCATSURL%
Job Order URL: %JBODCATSURL%

--
CATS
%SITENAME%

I wish to also include candidate attachments (resume) to this email as well, but I dont find that on the "Insert Mail Merge Fields"

Appreciate your kind considerations.

Cheers,
Rami

**Comment by Rami-Gaber** [comment]
Thanks alot, Shant! for your prompt responsiveness! Yea I think you are right, it is not feasible, the default way is what you suggested; to go directly to candidate's profile..

**Comment by shantadam** [comment]
I’m glad we managed to resolve your concern Rami 😊
Cheers!

Shant
