### ISSUE TITLE
Job board integrations

### ISSUE THREAD

**Issue by stephenstroud** [opencats/OpenCATS#479]
Does openCATS have the ability to send job listings to job boards like:

- Monster
- Reed
- Indeed
- Linkedin
- etc

**Comment by RussH** [comment]
Hi Stephen, 
whilst it doesn't have specific plugins for separate sites, it does expose RSS feeds and XML feeds which can be customised to the job board specifics. e.g. 

you can see the default XML feed here (from the project demo site)

https://demo.opencats.org/xml/  (Default is Indeed)
otherwise choose an alternative template;
https://demo.opencats.org/xml/?t=simplyhired

The templates (for SImplyHired & Indeed) are here;
https://github.com/opencats/OpenCATS/tree/master/modules/xml/xml_templates

If you can define a new template based upon the examples above for your new job board site, then we configure it in opencats;

MariaDB [opencats]> SELECT * FROM xml_feeds WHERE xml_feed_id=1

| xml_feed_id 1
| name Indeed
| description Indeed Job Search Engine
| website http://www.indeed.com
| post_url http://www.indeed.com/jsp/includejobs.jsp
| success_string "Thank you for submitting your XML job feed"
| xml_template_name indeed

**Comment by tonysamer2020** [comment]
for a beginner developer, what should I do to integrate careerbuilder to OpenCats?
please I'm badly asking for help,
thanks in advance Mr/Russ

**Comment by RussH** [comment]
@tonysamer2020  looks like careerbuilder shares it's XML feed spec here http://ws.careerbuilder.com/schemas/
