### ISSUE TITLE
Mailer.php syntax error

### ISSUE THREAD

**Issue by versigtm** [opencats/OpenCATS#513]
### Expected behavior and actual behavior.
PHP Parse Error

### Steps to reproduce the problem.
Run OpenCATS after install

### What version of opencats are you running? 
0.9.5.x

#### Release or downloaded from Git? 
downloaded from GIT

#### WAMP or LAMP? 
LAMP

### What version of PHP and MySQL are you running
PHP 7.4 and MariaDB 10

### attach appropriate error logs. Please attach [apache/mysql] error/access logs as needed.
PHP Parse error:  syntax error, unexpected 'alt' (T_STRING) in [...]/lib/Mailer.php on line 211

### solution
Escape the " sign before the alt attribute

**Comment by shantadam** [comment]
Indeed, good catch, @VersigTM. On the flip side, I'd like to reiterate the issue's solution, as such:

  *   On line 211 of <opencatsdir>/lib/Mailer.php escape with a back slash the closing quote character of the href attribute which is defined on the anchor html tag when code logic attempts to insert the email's signature body while requested.


Regards,

Shant Adam

<mailto:shant.adam@mxcgi.com>

<mailto:shant.adam@mxcgi.com>

________________________________

**Comment by shantadam** [comment]
It seems like the issue was recently resolved already by @KPull. See his pull request at https://github.com/opencats/OpenCATS/pull/511
[https://avatars0.githubusercontent.com/u/106173?s=400&v=4]<https://github.com/opencats/OpenCATS/pull/511>
Fix a syntax error in the Mailer.php file by KPull · Pull Request #511 · opencats/OpenCATS<https://github.com/opencats/OpenCATS/pull/511>
I've fixed an apparent syntax error in the Mailer.php file that is causing the system to fail to load when the SMTP mailing option is selected.
github.com


Regards,

Shant Adam

<mailto:shant.adam@mxcgi.com>

<mailto:shant.adam@mxcgi.com>

________________________________
