### ISSUE TITLE
ElementITMultiPowUpload1.7.swf

### ISSUE THREAD

**Issue by jaychaube** [opencats/OpenCATS#68]
The requested URL /recruitment/modules/asp/lib/MultiPowUpload/ElementITMultiPowUpload1.7.swf was not found on this server.

how to solve this error

**Comment by RussH** [comment]
Okay, so this part here relates to the *defunct* parsing service. There is a separate fork of opencats that appears to have a replacement parsing service bundled, but it's not (yet?) committed back to trunk. However this file (the flash uploader ) was not part of the opencats code (from memory) because th eoriginal developers had a licence but not to distribute as part of the Opensource version. It can now be downloaded from http://www.element-it.com/download.aspx?type=multipow and I assume would be a drop-in replacement (once you symlink ElementITMultiPowUpload.swf to ElementITMultiPowUpload1.7.swf). However - please note that this doesn't make resume parsing start workign, as th ebuilt-in parsing service has disappeared.
