### ISSUE TITLE
Support for newer version of MySql / MariaDB

### ISSUE THREAD

**Issue by skrchnavy** [opencats/OpenCATS#82]
OpenCATS supports Mysql/MariaDB 5.5.
Both are quite old (even supported) and some new features are missing there. 
Mysql 5.7 and 7.X is not working.
MySql and MariaDB are diverting now so there  could be also few issues related to support 2 different DBs.
see https://seravo.fi/2015/10-reasons-to-migrate-to-mariadb-if-still-using-mysql for more details.

**Comment by RussH** [comment]
I use MariaDB personally - I wouldn't imagine many installations use MySQL
through deliberate choice?



----
Russ

**Comment by amaisonneuve** [comment]
Interesting I use percona 5.5 in our production setup and it's working wonders.

What's the biggest advantage with Maria?

**Comment by RussH** [comment]
Percona's main advantage is ‎its version of InnoDB, which we're not using. Probably  simplest to pick one version of MySQL and support it. MariaDB, I chose this due to it being a fork from the original MySQL developer and he (was at the time) feature matching whatever oracle did and more. Not keen on choosing Oracles MySQL though.. one of the forks and we'll be fine!                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the O2 network.                                                                                                                                                                                                                From: Alain MaisonneuveSent: Saturday, 9 July 2016 14:43To: opencats/OpenCATSReply To: opencats/OpenCATSCc: RussH; CommentSubject: Re: [opencats/OpenCATS] Support for newer version of MySql / MariaDB (#82)Interesting I use percona 5.5 in our production setup and it's working wonders.

What's the biggest advantage with Maria? 

On July 8, 2016 5:58:29 AM EDT, RussH <notifications@github.com> wrote:
>I use MariaDB personally - I wouldn't imagine many installations use
>MySQL
>through deliberate choice?
>
>
>
>----
>Russ
>
>On 8 July 2016 at 07:56, Sveto Krchnavy <notifications@github.com>
>wrote:
>
>> OpenCATS supports Mysql/MariaDB 5.5.
>> Both are quite old (even supported) and some new features are missing
>> there.
>> Mysql 5.7 and 7.X is not working.
>> MySql and MariaDB are diverting now so there could be also few issues
>> related to support 2 different DBs.
>> see
>>
>https://seravo.fi/2015/10-reasons-to-migrate-to-mariadb-if-still-using-mysql
>> for more details.
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/opencats/OpenCATS/issues/82>, or mute the thread
>>
><https://github.com/notifications/unsubscribe/AARQfAEi_WOwrVCXn1g_HlIbUQFeYaT6ks5qTfSxgaJpZM4JHxR5>
>> .
>>
>
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/opencats/OpenCATS/issues/82#issuecomment-231322062


—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by RussH** [comment]
modern MySQL / MariaDB are now supported - closing aged issue.
